### ISSUE TITLE
Elastic search listen address

### ISSUE THREAD

**Issue by measwel** [strapdata/elassandra#152]
My setup: elassandra runs in a docker container, which runs inside DockerToolbox ( virtual box machine ) which in turn runs inside mac osx - the host. Inside DockerToolbox, the container is reachable on address 0.0.0.0:PORT.

In docker-compose.yml I have:

```
      environment:
          - CASSANDRA_CLUSTER_NAME=arbotti_cluster
          - CASSANDRA_SEEDS=DC1_CASSANDRA_SEED
          - CASSANDRA_PASSWORD_SEEDER=yes
          - CASSANDRA_PASSWORD=password123
          - CASSANDRA_DC=DC1
          - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
          - CASSANDRA_RACK=rack1
      # Exposing ports for inter cluster communication
      expose:
            - 7000
            - 7001
            - 7199
            - 9160
            - 9042
            - 9200
      # Exposing ports on host (docker toolbox) => host_port:docker_port
      ports:
        - "9042:9042"
        - "9200:9200"
```

Elastic search listens on 0.0.0.0:9200
Cassandra listens on 0.0.0.0:9042

In the firewall between the host and DockerToolbox, these ports are open. I can query both without problems from the host.

from the host: curl 0.0.0.0:9200 gives:

```
{
"name" : "172.18.0.3", <-- I DO NOT UNDERSTAND WHERE THIS COMES FROM
"cluster_name" : "arbotti_cluster",
"cluster_uuid" : "a0aa99db-c6a0-4823-b3de-f6e729a98e5c",
"version" : {
"number" : "5.5.0",
"build_hash" : "37f8692",
"build_date" : "2018-01-06T20:52:07.026Z",
"build_snapshot" : false,
"lucene_version" : "6.6.0"
},
"tagline" : "You Know, for Search"
}
```
Inside DockerToolbox: docker ps produces:
e93d0a8e2891 strapdata/elassandra "/docker-entrypoin..." 21 hours ago Up 21 hours 7000-7001/tcp, 7199/tcp, 0.0.0.0:9042->9042/tcp, 9160/tcp, 9300/tcp, 0.0.0.0:9200->9200/tcp a_DC1_CASSANDRA_SEED_1

In my application driver settings I have:

```
  elasticsearch: {
    apiVersion: '5.5',
    sniffOnStart: true,
    host: 'http://0.0.0.0:9200',
    requestTimeout: 60000
  }
```
However, the application (running on host) tries to reach elastic by the IP 172.18.0.3 and produces the error:

```
Elasticsearch ERROR: 2018-01-12T17:27:26Z
Error: Request error, retrying
HEAD http://172.18.0.3:9200/arbotti => socket hang up
```

It seems as if the driver ignores the elastic search IP setting and gets it from elastic instead. Elastic mentions: "name" : "172.18.0.3" in its response. Should I force elastic to listen on 0.0.0.0 ? Can somebody please explain why elastic mentions the address "172.18.0.3" in its response and how this can be changed?

**Comment by DBarthe** [comment]
Hi @measwel,

172.18.0.3 is probably the ip address of your container running elassandra.

0.0.0.0 just means elassandra is listening on every interfaces of the
container.

Since you mapped toolbox port 9200 to container port 9200, you should be
able to reach elassandra from the bare-metal host using the toolbox ip.

**Comment by measwel** [comment]
Yes that is correct. It is the container IP. But why is hostip 0.0.0.0 mentioned for port 9200 in the network settings from docker, while curl 0.0.0.0:9200 gives us:
```
{
"name" : "172.18.0.3",
...
"lucene_version" : "6.6.0"
},
"tagline" : "You Know, for Search"
}
```

Why is elastic mentioning 172.18.0.3 as the name? Elastic is not reachable at that IP. I can only reach it at 0.0.0.0. curl 172.18.0.3:9200 times out ...

The problem I have is that the db driver I am using tries to connect with elastic search over 172.18.0.3 instead of 0.0.0.0. How can I make sure elastic search is also reachable on the 172 IP address?

```
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d8a19a678f433c27aae5c201ef78408202bd69d9022094347c54f0b6598b034e",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "7000/tcp": null,
                "7001/tcp": null,
                "7199/tcp": null,
                "9042/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9042"
                    }
                ],
                "9160/tcp": null,
                "9200/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "9200"
                    }
                ],
                "9300/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/d8a19a678f43",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "a_DC1_NET": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "DC1_CASSANDRA_SEED",
                        "afd0e5680643"
                    ],
                    "NetworkID": "74e0303ec17d64f715f8ab96676955307d38901ba2e1755508cdd543a474b303",
                    "EndpointID": "97255259fea7f20a53a24a46ee253f90b60316af3c41b7d83bf9fe57326bf704",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:04",
                    "DriverOpts": null
                }
            }
        }
    }
```

**Comment by measwel** [comment]
I have pinned down the problem. It is caused by sniffOnStart in the elastic driver. This function gets the IP of the local elastic node ( which is the IP of the container running elassandra ) and overrides the 0.0.0.0 address set in config. For some reason elastic is only reachable via 0.0.0.0 but not via the IP of the container. 

How can I make sure elastic is also reachable by the IP of the container? My yml file looks like this:

```
  DC1_CASSANDRA_SEED:
      image: strapdata/elassandra
      restart: always      
      # image: 'bitnami/cassandra:latest'
      # sleep if starting for the first time. For each next node, sleep extra 60 sec.
      # command: bash -c 'if [ -z "$$(ls -A /var/lib/cassandra/)" ] ; then sleep 0; fi && /docker-entrypoint.sh cassandra -f'
      
      # map local folder for data persistency
      volumes:
        - /volumes/cassandra_seed_data:/var/lib/cassandra:rw

      # Docker container environment variable. We are using the
      # CASSANDRA_CLUSTER_NAME to name the cluster. This needs to be the same
      # across clusters. We are also declaring that DC1_CASSANDRA_SEED is a seed node.
      environment:
          - CASSANDRA_CLUSTER_NAME=arbotti_cluster
          - CASSANDRA_SEEDS=DC1_CASSANDRA_SEED
          - CASSANDRA_PASSWORD_SEEDER=yes
          - CASSANDRA_PASSWORD=password123
          - CASSANDRA_DC=DC1
          - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
          - CASSANDRA_RACK=rack1
      # Exposing ports for inter cluster communication
      expose:
            - 7000
            - 7001
            - 7199
            - 9160
            - 9042
            - 9200
      # Exposing ports on host (docker toolbox) => host_port:docker_port
      ports:
        - "9042:9042"
        - "9200:9200"
        
      # Cassandra ulimt recommended settings
      ulimits:
          memlock: -1
          nproc: 32768
          nofile: 100000
      
      # labels:
      # kompose.service.type: nodeport
        
      networks:
        - DC1_NET
```
