### ISSUE TITLE
unable run elassandra when updating 6.2.3.27 -> 6.8.4.4

### ISSUE THREAD

**Issue by jhekau** [strapdata/elassandra#340]
**Elassandra version**: 6.2.3.27

**JVM version** (`java -version`):
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**OS version** (`uname -a`): 
Linux db-cass 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
```
[main] ElassandraDaemon.java:601 main Exception
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.elasticsearch.common.network.NetworkAddress.format(NetworkAddress.java:93)
	at org.elasticsearch.common.network.NetworkAddress.format(NetworkAddress.java:69)
	at org.elassandra.discovery.CassandraDiscovery$GossipCluster.lambda$update$0(CassandraDiscovery.java:355)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at org.elassandra.discovery.CassandraDiscovery$GossipCluster.update(CassandraDiscovery.java:335)
	at org.elassandra.discovery.CassandraDiscovery$GossipCluster.update(CassandraDiscovery.java:310)
	at org.elassandra.discovery.CassandraDiscovery.doStart(CassandraDiscovery.java:446)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:72)
	at org.elasticsearch.node.Node.start(Node.java:797)
	at org.apache.cassandra.service.ElassandraDaemon.activate(ElassandraDaemon.java:215)
	at org.apache.cassandra.service.ElassandraDaemon.main(ElassandraDaemon.java:567)
```

/etc/cassandra/cassandra.yaml:
```
cluster_name: 'cluster'

num_tokens: 256
hinted_handoff_enabled: true
max_hint_window_in_ms: 10800000
hinted_handoff_throttle_in_kb: 1024
hints_flush_period_in_ms: 10000
max_hints_file_size_in_mb: 128
role_manager: CassandraRoleManager

partitioner: org.apache.cassandra.dht.Murmur3Partitioner
cdc_enabled: false

counter_cache_save_period: 7200

commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32

seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "10.10.1.11"

concurrent_reads: 32
concurrent_writes: 32
concurrent_counter_writes: 32

concurrent_materialized_view_writes: 32
memtable_allocation_type: heap_buffers

index_summary_resize_interval_in_minutes: 60
trickle_fsync: false
trickle_fsync_interval_in_kb: 10240
storage_port: 7000
ssl_storage_port: 7001

listen_address: 10.10.1.10
broadcast_address: 10.10.1.10

start_native_transport: true
native_transport_port: 9042

start_rpc: false
rpc_address: 10.10.1.10
rpc_port: 9160
rpc_keepalive: true
rpc_server_type: sync

thrift_framed_transport_size_in_mb: 15
incremental_backups: false
snapshot_before_compaction: false
auto_snapshot: true
column_index_size_in_kb: 64
column_index_cache_size_in_kb: 2
compaction_throughput_mb_per_sec: 16
sstable_preemptive_open_interval_in_mb: 50

read_request_timeout_in_ms: 50000
range_request_timeout_in_ms: 20000
write_request_timeout_in_ms: 20000
counter_write_request_timeout_in_ms: 5000
cas_contention_timeout_in_ms: 5000
truncate_request_timeout_in_ms: 60000
request_timeout_in_ms: 50000

slow_query_log_timeout_in_ms: 500

cross_node_timeout: false

streaming_socket_timeout_in_ms: 86400000

endpoint_snitch: SimpleSnitch

dynamic_snitch_update_interval_in_ms: 100
dynamic_snitch_reset_interval_in_ms: 600000
dynamic_snitch_badness_threshold: 0.1

request_scheduler: org.apache.cassandra.scheduler.NoScheduler

internode_compression: dc
inter_dc_tcp_nodelay: false
tracetype_query_ttl: 86400
tracetype_repair_ttl: 604800
enable_user_defined_functions: false
enable_scripted_user_defined_functions: false
enable_materialized_views: false
windows_timer_interval: 1

tombstone_warn_threshold: 1000
tombstone_failure_threshold: 100000
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
unlogged_batch_across_partitions_warn_threshold: 10
compaction_large_partition_warning_threshold_mb: 100
gc_warn_threshold_in_ms: 1000

back_pressure_enabled: false
back_pressure_strategy:
    - class_name: org.apache.cassandra.net.RateBasedBackPressure
      parameters:
        - high_ratio: 0.90
          factor: 5
          flow: FAST
```

/etc/hosts:
```
127.0.0.1	localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters

::1 db-cass db-cass
127.0.0.1 db-cass db-cass
```

**Steps to reproduce**:

current working version:
```
 "version" : {
      "number" : "6.2.3",
      "build_hash" : "706ae71",
      "build_date" : "2020-04-15T15:17:02.601140Z",
      "build_snapshot" : false,
      "lucene_version" : "7.2.1",
      "minimum_wire_compatibility_version" : "5.6.0",
      "minimum_index_compatibility_version" : "5.0.0"
 },
```

update:
```
$ service cassandra stop
$ apt install elassandra_6.8.4.4_all.deb
$ service cassandra start
```
